const actions = {
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	SET_AUTH_USER: "SET_AUTH_USER",
	REMOVE_AUTH_USER: "REMOVE_AUTH_USER",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL"
};

export default actions;
