const actions = {
	ADD_CONTACT: "ADD_CONTACT",
	UPDATE_CONTACT: "UPDATE_CONTACT",
	SET_UPDATE_CONTACT: "SET_UPDATE_CONTACT",
	DELETE_CONTACT: "DELETE_CONTACT",
	FILTER_CONTACTS: "FILTER_CONTACTS",
	CLEAR_FILTER: "CLEAR_FILTER"
};

export default actions;
